const Express = require("express");
const cdn = Express.Router();
const config = require("config");
const cache = require("express-disk-cache")(config.cache_directory);
const root = require("helper/rootDir");
const { join } = require("path");

var documentation_static_files = join(root, "/app/documentation/data/views");
var static_files_directory = join(root, "/app/blog/static");

// This route is used by Blot's CDN (AWS Cloudfront) to retrieve
// static assets generated by Blot and serve them to your readers.
// A request to:
//
// https://blotcdn.com/{blogID}/path-to/file.jpg
//
// Will have its SSl terminated by Cloudfront close to the user.
// Cloudfront will then request the following URL from Blot's
// main server and send back the response:
//
// https://blot.im/static/{blogID}/path-to/file.jpg
//
// Cloudfront will store this response to server future requests

if (config.cache) cdn.use(cache);

cdn

  // These files are generated by Blot and their paths contain GUIDs.
  // They never change and can be cached forever.
  .use(
    Express.static(config.blog_static_files_dir, {
      immutable: true,
      maxAge: "31536000",
      lastModified: false,
      etag: false,
    })
  )
  
  .use(
    "/documentation/:cacheid/",
    Express.static(documentation_static_files, {
      index: false, // Without 'index: false' this will server the index.html files inside
      redirect: false, // Without 'redirect: false' this will redirect URLs to existent directories
      maxAge: 86400000,
      setHeaders: function (res) {
        res.setHeader("Access-Control-Allow-Origin", "*");
      },
    })
  )

  .use(
    Express.static(static_files_directory, {
      immutable: true,
      maxAge: "31536000",
      lastModified: false,
      etag: false,
      setHeaders: function (res) {
        res.setHeader("Access-Control-Allow-Origin", "*");
      },
    })
  )

  .use(function (req, res) {
    res.status(404).send("404: Not found");
  })

  .use(function (err, req, res, next) {
    res.status(400).send("400: Bad request");
  });

// It might be nice to add a route which can render CSS and JS
// on a particular template
module.exports = cdn;
