# Default request rate limits for non-preview traffic.
# CDN IPs are whitelisted via $limit/$host_limit_key maps.

# We'll buffer up to 30 requests over the 6/second limit per specific IP until returning 429 errors
limit_req zone=general burst=30;

# We'll buffer up to 30 requests over the 10/second limit for a specific hostname until returning 429 errors
limit_req zone=hostlimit burst=30;

limit_req_status 429;
