import readline from "readline";
import { iCloudDriveDirectory } from "./config.js";
import { spawn } from "child_process";
import recursiveList from "./util/recursiveList.js";
import clfdate from "./util/clfdate.js";
import { isEvictionSuppressed } from "./evictionSuppression.js";
import { isActive } from "./watcher/activeBlogs.js";

// The purpose of this module is to keep iCloud Drive in sync
// and it achieves this by running `brctl monitor` to detect blog
// folders with changes and then it recursively lists their contents
// in order to force iCloud to sync the contents of the folder. It seems
// like using ls as opposed to readdir actually forces iCloud drive to
// push the names of new files and folders to the local system.

// If eventually we run into scaling issues with chokidar we could potentially
// use the information generated by this module to trigger syncs...
export default () => {
  function startMonitor() {
    const monitorProcess = spawn("brctl", [
      "monitor",
      "-i"
    ]);

    const rl = readline.createInterface({
      input: monitorProcess.stdout,
      crlfDelay: Infinity,
    });

    rl.on("line", (line) => {
      const match = line.match(/blog_[a-fA-F0-9]+/);

      // non-matching lines are either blank or contain
      // a date and time for the subsequent line or 
      // refer to files outside a specific blog directory
      if (match) {
        console.log(clfdate(), `brctl monitor event: ${line}`);

        const blogId = match[0];

        if (isEvictionSuppressed(blogId)) {
          console.log(
            clfdate(),
            `Ignoring brctl monitor event during eviction suppression: ${blogId}`
          );
          return;
        }

        if (!isActive(blogId)) {
          console.log(
            clfdate(),
            `Dropping brctl monitor event for inactive blogID: ${blogId}`
          );
          return;
        }

        recursiveList(`${iCloudDriveDirectory}/${blogId}`, 0).catch((error) => {
          console.error(clfdate(), 
            `Failed to recursively list contents of ${blogId}:`,
            error
          );
        });
      }
    });

    monitorProcess.stderr.on("data", (data) => {
      console.error(clfdate(), `stderr: ${data}`);
    });

    monitorProcess.on("close", (code) => {
      rl.close();
      console.warn(clfdate(), 
        `brctl monitor exited with code ${code}, restarting in 1s...`
      );
      setTimeout(startMonitor, 1000);
    });
  }

  startMonitor();
};
