module.exports = [

    "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--font-render-hinting=none",
      "--force-color-profile=srgb",


    // // cache
    // "--disable-dev-profile",
    // "--aggressive-cache-discard",
    // "--disable-cache",
    // "--disable-application-cache",
    // "--disable-offline-load-stale-cache",
    // "--disable-gpu-shader-disk-cache",
    // "--media-cache-size=0",
    // "--disk-cache-size=0",
    // // performance
    // "--disable-infobars",
    // "--no-sandbox",
    // "--disable-gpu",
    // "--disable-setuid-sandbox",
    // "--no-zygote",
    // "--disable-extensions",
    // "--disable-plugins",
    // "--headless",
    // "--disable-breakpad",
    // "--disable-client-side-phishing-detection",
    // "--disable-sync",
    // "--disable-translate",
    // "--no-experiments",
    // "--disable-default-apps",
    // "--mute-audio",
    // "--no-default-browser-check",
    // "--disable-background-timer-throttling",
    // "--disable-backgrounding-occluded-windows",
    // "--disable-notifications",
    // "--disable-background-networking",
    // "--disable-component-update",
    // "--disable-domain-reliability",
    // "--autoplay-policy=user-gesture-required",
    // "--disable-component-extensions-with-background-pages",
    // // rendering
    // "--deterministic-fetch",
    // "--hide-scrollbars",
    // "--font-render-hinting=none",
  ];