var Express = require("express");
var dashboard = require("./dashboard");
var documentation = require("./documentation");
var cdn = require("./cdn");
var site = Express();

// The dashboard
// -------
site.use("/dashboard", dashboard);

// The CDN
// -------
// Serves static files generated by Blot e.g.
// thumbnails and cached images.
site.use("/cdn", cdn);

// The client requests handler
site.use("/clients", require("clients/routes"));

// The stripe webhook handler
site.use("/stripe-webhook", require("./dashboard/stripe_webhook"));

// The documentation
// ------------
// The least important application. It serves the documentation
site.use(documentation);

module.exports = site;
