const mustache = require("mustache");
const config = require("config");
const fs = require("fs-extra");

const NODE_PRIVATE_IP = process.env.NODE_PRIVATE_IP;
const REDIS_PRIVATE_IP = process.env.REDIS_PRIVATE_IP;

const OUTPUT = __dirname + "/data";
const CONFIG_DIRECTORY = __dirname + "/conf";

const template = fs.readFileSync(`${CONFIG_DIRECTORY}/server.conf`, "utf8");
const partials = {};
const locals = {
  blot_directory: config.blot_directory,
  // development: config.environment === "development",
  host: "blot.im",
  node_ip: NODE_PRIVATE_IP,
  node_port: config.port,
  redis: { host: REDIS_PRIVATE_IP },
  user: "ec2-user",
  config_directory: "/home/ec2-user/openresty",
  // if you change the cache directory, you must also update the
  // script mount-instance-store.sh
  cache_directory: "/var/www/cache",
  ssl_certificate: "/etc/ssl/private/letsencrypt-domain.pem",
  ssl_certificate_key: "/etc/ssl/private/letsencrypt-domain.key"
};

if (!NODE_PRIVATE_IP) throw new Error("NODE_PRIVATE_IP not set");
if (!REDIS_PRIVATE_IP) throw new Error("REDIS_PRIVATE_IP not set");

fs.emptyDirSync(OUTPUT);

fs.copySync(`${__dirname}/html`, `${__dirname}/data/html`);

fs.readdirSync(CONFIG_DIRECTORY).forEach(file => {
  // copy lua files to data directory so they are available to nginx
  if (file.endsWith(".lua")) {
    const lua = fs.readFileSync(`${CONFIG_DIRECTORY}/${file}`, "utf8");
    const result = mustache.render(lua, locals);
    fs.outputFileSync(`${OUTPUT}/${file}`, result);
  }

  if (!file.endsWith(".conf")) return;
  partials[file] = fs.readFileSync(CONFIG_DIRECTORY + "/" + file, "utf8");
});

const warning = `

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!   WARNING                                   !!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# Do not edit this file directly

# This file was generated by ../build.js
# Please update the source files in ./conf and run ../build.js

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!   WARNING                                   !!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

`;

const result = mustache.render(template, locals, partials);

fs.outputFileSync(__dirname + "/data/openresty.conf", warning + result);
