name: Benchmark

on:
  pull_request:
    branches:
      - master

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Run the benchmark
      - name: Run benchmark
        run: npm run benchmark