name: build

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

permissions:
  contents: read
  packages: write

jobs:
  build-production-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build production image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          target: prod
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/blot
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/blot,mode=max
          tags: ghcr.io/${{ github.repository_owner }}/blot:${{ github.sha }}

      - name: Verify built-in health check
        env:
          IMAGE: ghcr.io/${{ github.repository_owner }}/blot:${{ github.sha }}
        run: |
          docker network create test_network

          redis_container_id=$(docker run -d --name test_redis --network test_network redis:latest)

          if [ -z "$redis_container_id" ]; then
            echo "Failed to start the Redis container. Exiting..."
            exit 1
          fi

          echo "Waiting for Redis ($redis_container_id) to become ready..."
          timeout=30
          interval=2
          elapsed=0
          while ! docker exec $redis_container_id redis-cli ping | grep -q PONG; do
            if [ $elapsed -ge $timeout ]; then
              echo "Redis did not become ready within $timeout seconds. Exiting..."
              docker stop $redis_container_id
              docker rm $redis_container_id
              exit 1
            fi
            sleep $interval
            elapsed=$((elapsed + interval))
          done
          echo "Redis is ready."

          container_id=$(docker run -d --network test_network --env BLOT_REDIS_HOST=test_redis -p 8080:8080 $IMAGE)

          if [ -z "$container_id" ]; then
            echo "Failed to start the app container. Exiting..."
            docker stop $redis_container_id
            docker rm $redis_container_id
            exit 1
          fi

          echo "Waiting for the app container ($container_id) to pass the built-in health check..."

          timeout=60
          interval=5
          elapsed=0
          while [ "$(docker inspect --format='{{json .State.Health.Status}}' $container_id)" != '"healthy"' ]; do
            if [ $elapsed -ge $timeout ]; then
              echo "Health check failed: app container did not become healthy within $timeout seconds."

              echo "Final log contents:"
              docker logs $container_id
              docker stop $container_id
              docker rm $container_id
              docker stop $redis_container_id
              docker rm $redis_container_id
              exit 1
            fi
            sleep $interval
            elapsed=$((elapsed + interval))
          done

          echo "App container passed the health check."

          docker stop $container_id
          docker rm $container_id
          docker stop $redis_container_id
          docker rm $redis_container_id
