name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: write

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/blot
  SHOULD_PUSH: ${{ github.event_name != 'pull_request' }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            runs-on: ubuntu-latest
          - arch: arm64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      # 1) Build for local use (no push), then test it
      - name: Build (load locally) ${{ matrix.arch }}
        id: build_local
        uses: docker/build-push-action@v6
        with:
          context: .
          target: prod
          platforms: ${{ matrix.platform }}   # single-arch, so load works
          load: true                          # image available to `docker run`
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          cache-from: |
            type=gha,scope=${{ matrix.arch }}
            type=registry,ref=${{ env.IMAGE_NAME }}:cache-${{ matrix.arch }}
          cache-to: |
            type=gha,scope=${{ matrix.arch }},mode=max
          provenance: false

      - name: Verify health check (${{ matrix.arch }})
        env:
          IMAGE: ${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
        run: |
          set -euo pipefail
          docker network create test_network
          redis_container_id=$(docker run -d --name test_redis --network test_network redis:7-alpine)
          timeout=30; interval=2; elapsed=0
          until docker exec "$redis_container_id" redis-cli ping | grep -q PONG; do
            if [ $elapsed -ge $timeout ]; then
              echo "Redis not ready in $timeout s"
              docker logs "$redis_container_id" || true
              exit 1
            fi
            sleep $interval; elapsed=$((elapsed+interval))
          done
          app_id=$(docker run -d --network test_network -e BLOT_REDIS_HOST=test_redis -p 8080:8080 "$IMAGE")
          timeout=60; interval=5; elapsed=0
          until [ "$(docker inspect --format='{{json .State.Health.Status}}' "$app_id")" = '"healthy"' ]; do
            if [ $elapsed -ge $timeout ]; then
              echo "App health check failed"
              docker logs "$app_id" || true
              exit 1
            fi
            sleep $interval; elapsed=$((elapsed+interval))
          done
          docker rm -f "$app_id" "$redis_container_id"
          docker network rm test_network

      # 2) Push only on non-PRs; reuses cache so it’s fast
      - name: Build and push ${{ matrix.arch }}
        if: env.SHOULD_PUSH == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          target: prod
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          cache-from: |
            type=gha,scope=${{ matrix.arch }}
            type=registry,ref=${{ env.IMAGE_NAME }}:cache-${{ matrix.arch }}
          cache-to: |
            type=registry,ref=${{ env.IMAGE_NAME }}:cache-${{ matrix.arch }},mode=max
          provenance: false

  manifest:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && needs.build.result == 'success'
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and push multi-arch manifest
        run: |
          set -euo pipefail
          IMAGE="ghcr.io/${{ github.repository_owner }}/blot"
          SHA="${{ github.sha }}"
          docker buildx imagetools create \
            -t "$IMAGE:$SHA" \
            "$IMAGE:$SHA-amd64" \
            "$IMAGE:$SHA-arm64"
          if [ "${{ github.ref_name }}" = "master" ]; then
            docker buildx imagetools create -t "$IMAGE:latest" "$IMAGE:$SHA"
          fi
