name: cacher-tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: leafo/gh-actions-openresty@v1
        with:
          openrestyVersion: "1.21.4.2"
          configureFlags: "--with-pcre-jit --with-ipv6 --with-http_v2_module"

      - uses: leafo/gh-actions-luarocks@v4
        with:
          withLuaPath: "/usr/local/openresty/luajit/"

      - name: install auto-ssl
        run: |
          which luarocks
          sudo /home/runner/work/Blot/Blot/.luarocks/bin/luarocks install lua-resty-auto-ssl
          sudo /home/runner/work/Blot/Blot/.luarocks/bin/luarocks list
          luarocks show lua-resty-auto-ssl

      - name: Set up Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: 6.2.6

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Load dependencies
        uses: actions/cache@v2
        id: cache-node-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-node-dependencies.outputs.cache-hit != 'true'
        env:
          PUPETEER_PRODUCT: firefox
        run: npm ci

      - name: run cacher tests
        env:
          NODE_PATH: /home/runner/work/Blot/Blot/app
          BLOT_OPENRESTY_TEST_USER: runner
          BLOT_OPENRESTY_TEST_GROUP: runner
        run: |
          npm test config/openresty/conf/cacher
