name: Test Docker Image

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - "Dockerfile" # Ignore changes to Dockerfile in this workflow
  push:
    branches: [master]
    paths-ignore:
      - "Dockerfile" # Ignore changes to Dockerfile in this workflow

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Redis network name
        id: redis_network
        run: echo "::set-output name=network_name::$(docker network ls --filter name=_default -q)"

      - name: Run npm test inside the container
        run: |
          docker run --rm \
            --network name=${{ job.services.redis.network }} \
            -e BLOT_REDIS_HOST=redis \
            ghcr.io/${{ github.repository_owner }}/blot:latest  sh -c "\
            git config --global user.email 'you@example.com' && \
            git config --global user.name 'Your Name' && \
            node app/setup && npm test"
