name: Unused dependency check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2

      - name: Check for unused dependencies
        # This command will check for unused dependencies and exit with a non-zero status if any are found
        # we use the --skip-missing flag to ignore missing dependencies
        # we use the --ignores flag to ignore certain dependencies which depcheck
        # fails to detect since they're using in forked processes
        run: npx depcheck --ignores=nodemon,blessed-contrib,twit,fontkit,text-to-svg --skip-missing
