on:
  push:
    tags:
    - '*'
    
name: Zip up folders for distribution
jobs:
  build:
    name: Zip up folders for distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Zip files
        run: |
          zip -r bjorn.zip app/templates/folders/bjorn/
          zip -r david.zip app/templates/folders/david/
          zip -r frances.zip app/templates/folders/frances/
          zip -r interviews.zip app/templates/folders/interviews/
          zip -r william.zip app/templates/folders/william/
          
      - run: |
          set -x
          assets=()
          for asset in ./*.zip; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
